name: Everty 10 Minutes Process Tips

on:
  workflow_dispatch:
  schedule:
    - cron: '7/10 * * * *' 

env:
  CLIENT_ID: ${{secrets.CLIENT_ID}}
  CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
  REDDIT_NAME: ${{secrets.REDDIT_NAME}}
  PASSWORD: ${{secrets.PASSWORD}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Process laterst tips
        run: python code/download_comments.py
        
      - name: Create leaderboards
        run: python code/create_leaderboard.py

      - name: commit data
        uses: EndBug/add-and-commit@v9
        with:
          message: Update leaderboard
          committer_name: GitHub Actions
          committer_email: actions@github.com
